// REACT CODE/src/app/pages/EventDetails.tsx
import { useLocation } from "react-router-dom";
import Navbar from "../layout/Navbar";

const EventDetails = () => {
  const location: any = useLocation();

  return (
    <section>
      <Navbar />
      <div className="container">
        <div className="row">
          <div className="col-md-12 mt-3">
            <img src={location.state.img_url} alt="" className="img-fluid" />
          </div>
          <div className="col-md-12 mt-4">
            <h1 className="text-center fw-bold">{location.state.name}</h1>
            <p className="text-center">{location.state.description}</p>
            <p className="text-center">
              <img
                src={require("../../assets/img/date.png")}
                alt=""
                className="img-fluid"
                style={{ width: "25px" }}
              />
              {location.state.startDate}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default EventDetails;

// VUE CODE/src/views/EventDetails.vue
<template>
  <div class="event p-5">
    <img :src="eventData.img_url">
    <h1 class="text-3xl font-bold underline text-center	">
    {{eventData.name}}
    </h1>
    <h2>
       Start Date: {{eventData.startDate}}
    </h2>
    <h2>
       End Date:  {{eventData.endDate}}
    </h2>
    <h1>
        Event Description : {{eventData.description}}
    </h1>
  </div>
</template>

<script setup>  
import { ref } from "vue"
import { useRoute } from 'vue-router'
const route = useRoute()
const eventData = ref(route.params)
</script>
